#!/usr/bin/env python

import os
import sys

from argparse import ArgumentParser

def make_parser():
    parser = ArgumentParser(description="Make a symbolic link from something to something, without having to specify the order. Exactly one of the two arguments must exist.")
    parser.add_argument("one")
    parser.add_argument("two")
    return parser

def main():
    parser = make_parser()
    args = parser.parse_args()

    if os.path.exists(args.one):
        filename, linkname = args.one, args.two
    elif os.path.exists(args.two):
        linkname, filename = args.one, args.two
    else:
        sys.exit("Exactly one of the two arguments must exist.")

    os.symlink(filename, linkname)

if __name__ == '__main__':
    sys.exit(main())
