#!/usr/bin/env python

import os
import sys

from argparse import ArgumentParser

def make_parser():
    parser = ArgumentParser(description="Make a symbolic link from something to something, without having to specify the order. Exactly one of the two arguments must exist.")
    parser.add_argument("one")
    parser.add_argument("two")
    return parser

def main():
    parser = make_parser()
    args = parser.parse_args()

    exists = map(os.path.exists, [args.one, args.two])

    if exists[0] == exists[1]:
        sys.exit("Exactly one of the two arguments must exist.")
    elif exists[0]:
        filename, linkname = args.one, args.two
    else:
        linkname, filename = args.one, args.two

    os.symlink(filename, linkname)

if __name__ == '__main__':
    sys.exit(main())
