#!/bin/bash -eu

PID=$1
SAMPLES=${2-10}
SLEEPTIME=${3-0}

for ((i=0; i<SAMPLES; i++)); do
    (echo "set pagination 0"; 
     echo "thread apply all bt"; 
     echo "quit"; cat /dev/zero) | gdb -p $PID 2> /dev/null
    sleep $SLEEPTIME
done | \
awk '
  BEGIN { s = ""; } 
  /^Thread/ { print s; s = ""; } 
  /^\#/ { if (s != "" ) { s = s "," $4} else { s = $4 } } 
  END { print s }' | \
sed '/^$/d' | sort | uniq -c | sort -r -n
